# Generated by Django 4.2.6 on 2023-10-11 00:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('walletapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.UUID('2aa88e02-67cc-11ee-9572-f69c58ab96f9'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=uuid.UUID('2aa89b0e-67cc-11ee-9572-f69c58ab96f9'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CustAuthToken',
            fields=[
                ('token_id', models.CharField(default=uuid.UUID('2aa8a522-67cc-11ee-9572-f69c58ab96f9'), max_length=50, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletapi.account')),
            ],
        ),
    ]
