# Generated by Django 4.2.6 on 2023-10-11 02:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('walletapi', '0003_rename_changed_at_account_enabled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.UUID('1520c0c8-67df-11ee-a646-f69c58ab96f9'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='custauthtoken',
            name='token_id',
            field=models.CharField(default=uuid.UUID('1520d8d8-67df-11ee-a646-f69c58ab96f9'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=uuid.UUID('1520cdde-67df-11ee-a646-f69c58ab96f9'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
