# Generated by Django 4.2.6 on 2023-10-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapi', '0005_alter_account_id_alter_custauthtoken_token_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custauthtoken',
            old_name='token_id',
            new_name='token',
        ),
    ]
